import flet as ft

WINDOW_WIDTH = 600
WINDOW_HEIGHT = 400

BOX_HEIGHT_COLLAPSED = 120
BOX_HEIGHT_EXPANDED = 220
BOX_WIDTH = 600

BG_COLOR = ft.Colors.WHITE

TEXT_COLOR = ft.Colors.BLACK
CONTAINER_BG_COLOR = ft.Colors.BLUE_GREY_500
CONTAINER_DROP_SHADOW = ft.Colors.BLACK_87
